# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: for_three_db
  pool: 5
  username: postgres
  password: charley

test:
  adapter: postgresql
  encoding: unicode
  database: for_three_db_test
  pool: 5
  username: postgres
  password: charley

production:
  adapter: postgresql
  encoding: unicode
  database: for_three_db
  pool: 5
  username: postgres
  password: charley

